package setup

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"cloud-update/src/internal/infrastructure/system"
)

const (
	InstallDir = "/opt/cloud-update"
	ConfigDir  = "/etc/cloud-update"
	BinaryName = "cloud-update"
)

type ServiceInstaller struct {
	distro     system.Distribution
	initSystem InitSystem
}

type InitSystem string

const (
	InitSystemd  InitSystem = "systemd"
	InitOpenRC   InitSystem = "openrc"
	InitSysVInit InitSystem = "sysvinit"
	InitUpstart  InitSystem = "upstart"
	InitUnknown  InitSystem = "unknown"
)

func NewServiceInstaller() *ServiceInstaller {
	return &ServiceInstaller{
		distro:     detectDistribution(),
		initSystem: detectInitSystem(),
	}
}

func (s *ServiceInstaller) Setup() error {
	fmt.Println("🚀 Cloud Update Service Setup")
	fmt.Printf("📦 Detected: %s with %s\n", s.distro, s.initSystem)

	// Check if running as root
	if os.Geteuid() != 0 && runtime.GOOS != "windows" {
		return fmt.Errorf("setup must be run as root (use sudo)")
	}

	// Create directories
	if err := s.createDirectories(); err != nil {
		return fmt.Errorf("failed to create directories: %w", err)
	}

	// Copy binary
	if err := s.installBinary(); err != nil {
		return fmt.Errorf("failed to install binary: %w", err)
	}

	// Install service files
	if err := s.installService(); err != nil {
		return fmt.Errorf("failed to install service: %w", err)
	}

	// Create config file
	if err := s.createConfig(); err != nil {
		return fmt.Errorf("failed to create config: %w", err)
	}

	// Enable service
	if err := s.enableService(); err != nil {
		return fmt.Errorf("failed to enable service: %w", err)
	}

	fmt.Println("✅ Setup completed successfully!")
	s.printNextSteps()

	return nil
}

func (s *ServiceInstaller) createDirectories() error {
	fmt.Println("📁 Creating directories...")

	dirs := []struct {
		path string
		mode os.FileMode
	}{
		{InstallDir, 0o755},
		{ConfigDir, 0o700},
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir.path, dir.mode); err != nil {
			return err
		}
		fmt.Printf("  ✓ %s\n", dir.path)
	}

	return nil
}

func (s *ServiceInstaller) installBinary() error {
	fmt.Println("📦 Installing binary...")

	// Get current executable path
	execPath, err := os.Executable()
	if err != nil {
		return err
	}

	destPath := filepath.Join(InstallDir, BinaryName)

	// Copy binary
	input, err := os.ReadFile(execPath) // #nosec G304 - execPath comes from os.Executable()
	if err != nil {
		return err
	}

	// Binary needs executable permissions
	// #nosec G306 -- binary must be executable (755)
	if err := os.WriteFile(destPath, input, 0o755); err != nil {
		return err
	}

	fmt.Printf("  ✓ Installed to %s\n", destPath)
	return nil
}

func (s *ServiceInstaller) installService() error {
	fmt.Printf("🔧 Installing %s service...\n", s.initSystem)

	switch s.initSystem {
	case InitSystemd:
		return s.installSystemdService()
	case InitOpenRC:
		return s.installOpenRCService()
	case InitSysVInit:
		return s.installSysVInitService()
	default:
		return fmt.Errorf("unsupported init system: %s", s.initSystem)
	}
}

func (s *ServiceInstaller) installSystemdService() error {
	servicePath := "/etc/systemd/system/cloud-update.service"

	// Systemd service files need 0644 permissions
	// #nosec G306 -- systemd requires 0644 permissions
	if err := os.WriteFile(servicePath, []byte(SystemdService), 0o644); err != nil {
		return err
	}

	// Reload systemd
	if err := exec.Command("systemctl", "daemon-reload").Run(); err != nil {
		return fmt.Errorf("failed to reload systemd: %w", err)
	}

	fmt.Printf("  ✓ Installed systemd service to %s\n", servicePath)
	return nil
}

func (s *ServiceInstaller) installOpenRCService() error {
	servicePath := "/etc/init.d/cloud-update"

	// Init scripts need executable permissions
	// #nosec G306 -- init scripts must be executable (755)
	if err := os.WriteFile(servicePath, []byte(OpenRCScript), 0o755); err != nil {
		return err
	}

	fmt.Printf("  ✓ Installed OpenRC service to %s\n", servicePath)
	return nil
}

func (s *ServiceInstaller) installSysVInitService() error {
	servicePath := "/etc/init.d/cloud-update"

	// Init scripts need executable permissions
	// #nosec G306 -- init scripts must be executable (755)
	if err := os.WriteFile(servicePath, []byte(SysVInitScript), 0o755); err != nil {
		return err
	}

	// Update rc.d if available
	if _, err := exec.LookPath("update-rc.d"); err == nil {
		_ = exec.Command("update-rc.d", "cloud-update", "defaults").Run()
	}

	fmt.Printf("  ✓ Installed SysVInit service to %s\n", servicePath)
	return nil
}

func (s *ServiceInstaller) createConfig() error {
	fmt.Println("⚙️  Creating configuration...")

	configPath := filepath.Join(ConfigDir, "config.env")

	// Check if config already exists
	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("  ⚠️  Config already exists at %s\n", configPath)
		return nil
	}

	// Generate secret
	secret := generateSecret()

	config := fmt.Sprintf(`# Cloud Update Configuration
# Generated by setup command

# Port on which the HTTP server will listen
CLOUD_UPDATE_PORT=9999

# Secret key for webhook signature validation (HMAC SHA256)
CLOUD_UPDATE_SECRET=%s

# Log level (debug, info, warn, error)
CLOUD_UPDATE_LOG_LEVEL=info
`, secret)

	if err := os.WriteFile(configPath, []byte(config), 0o600); err != nil {
		return err
	}

	// Set ownership to root
	if err := os.Chown(configPath, 0, 0); err != nil {
		return err
	}

	fmt.Printf("  ✓ Created config at %s\n", configPath)
	fmt.Printf("  🔑 Generated secret: %s\n", secret)

	return nil
}

func (s *ServiceInstaller) enableService() error {
	fmt.Println("🔌 Enabling service...")

	var cmd *exec.Cmd

	switch s.initSystem {
	case InitSystemd:
		cmd = exec.Command("systemctl", "enable", "cloud-update")
	case InitOpenRC:
		cmd = exec.Command("rc-update", "add", "cloud-update", "default")
	case InitSysVInit:
		if _, err := exec.LookPath("update-rc.d"); err == nil {
			cmd = exec.Command("update-rc.d", "cloud-update", "enable")
		} else {
			fmt.Println("  ⚠️  Please manually enable the service")
			return nil
		}
	default:
		fmt.Printf("  ⚠️  Cannot auto-enable for %s\n", s.initSystem)
		return nil
	}

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to enable service: %w", err)
	}

	fmt.Println("  ✓ Service enabled")
	return nil
}

func (s *ServiceInstaller) printNextSteps() {
	fmt.Println("\n📋 Next steps:")
	fmt.Printf("1. Review configuration: %s\n", filepath.Join(ConfigDir, "config.env"))

	switch s.initSystem {
	case InitSystemd:
		fmt.Println("2. Start service: sudo systemctl start cloud-update")
		fmt.Println("3. Check status: sudo systemctl status cloud-update")
		fmt.Println("4. View logs: sudo journalctl -u cloud-update -f")
	case InitOpenRC:
		fmt.Println("2. Start service: sudo rc-service cloud-update start")
		fmt.Println("3. Check status: sudo rc-service cloud-update status")
		fmt.Println("4. View logs: tail -f /var/log/cloud-update.log")
	case InitSysVInit:
		fmt.Println("2. Start service: sudo service cloud-update start")
		fmt.Println("3. Check status: sudo service cloud-update status")
		fmt.Println("4. View logs: tail -f /var/log/syslog | grep cloud-update")
	}
}

func (s *ServiceInstaller) Uninstall() error {
	fmt.Println("🗑️  Uninstalling Cloud Update Service")

	// Stop service
	s.stopService()

	// Disable service
	s.disableService()

	// Remove service files
	s.removeServiceFiles()

	// Remove binary
	if err := os.RemoveAll(InstallDir); err != nil {
		fmt.Printf("  ⚠️  Failed to remove %s: %v\n", InstallDir, err)
	} else {
		fmt.Printf("  ✓ Removed %s\n", InstallDir)
	}

	// Ask about config
	fmt.Printf("\n❓ Remove configuration directory %s? (y/N): ", ConfigDir)
	var response string
	_, _ = fmt.Scanln(&response)
	if strings.EqualFold(response, "y") {
		if err := os.RemoveAll(ConfigDir); err != nil {
			fmt.Printf("  ⚠️  Failed to remove %s: %v\n", ConfigDir, err)
		} else {
			fmt.Printf("  ✓ Removed %s\n", ConfigDir)
		}
	}

	fmt.Println("✅ Uninstall completed")
	return nil
}

func (s *ServiceInstaller) stopService() {
	fmt.Println("⏹️  Stopping service...")

	var cmd *exec.Cmd
	switch s.initSystem {
	case InitSystemd:
		cmd = exec.Command("systemctl", "stop", "cloud-update")
	case InitOpenRC:
		cmd = exec.Command("rc-service", "cloud-update", "stop")
	case InitSysVInit:
		cmd = exec.Command("service", "cloud-update", "stop")
	default:
		return
	}

	if err := cmd.Run(); err != nil {
		fmt.Printf("  ⚠️  Failed to stop service: %v\n", err)
	} else {
		fmt.Println("  ✓ Service stopped")
	}
}

func (s *ServiceInstaller) disableService() {
	fmt.Println("🔌 Disabling service...")

	var cmd *exec.Cmd
	switch s.initSystem {
	case InitSystemd:
		cmd = exec.Command("systemctl", "disable", "cloud-update")
	case InitOpenRC:
		cmd = exec.Command("rc-update", "del", "cloud-update")
	case InitSysVInit:
		if _, err := exec.LookPath("update-rc.d"); err == nil {
			cmd = exec.Command("update-rc.d", "-f", "cloud-update", "remove")
		}
	}

	if cmd != nil {
		if err := cmd.Run(); err != nil {
			fmt.Printf("  ⚠️  Failed to disable service: %v\n", err)
		} else {
			fmt.Println("  ✓ Service disabled")
		}
	}
}

func (s *ServiceInstaller) removeServiceFiles() {
	fmt.Println("📄 Removing service files...")

	var servicePath string
	switch s.initSystem {
	case InitSystemd:
		servicePath = "/etc/systemd/system/cloud-update.service"
		defer func() { _ = exec.Command("systemctl", "daemon-reload").Run() }()
	case InitOpenRC, InitSysVInit:
		servicePath = "/etc/init.d/cloud-update"
	}

	if servicePath != "" {
		if err := os.Remove(servicePath); err != nil {
			fmt.Printf("  ⚠️  Failed to remove %s: %v\n", servicePath, err)
		} else {
			fmt.Printf("  ✓ Removed %s\n", servicePath)
		}
	}
}

func detectDistribution() system.Distribution {
	executor := system.NewSystemExecutor()
	return executor.DetectDistribution()
}

func detectInitSystem() InitSystem {
	// Check for systemd
	if _, err := os.Stat("/run/systemd/system"); err == nil {
		return InitSystemd
	}

	// Check for OpenRC
	if _, err := exec.LookPath("openrc"); err == nil {
		return InitOpenRC
	}

	// Check for Upstart
	if _, err := os.Stat("/etc/init"); err == nil {
		if _, err := exec.LookPath("initctl"); err == nil {
			return InitUpstart
		}
	}

	// Check for SysVInit
	if _, err := os.Stat("/etc/init.d"); err == nil {
		return InitSysVInit
	}

	return InitUnknown
}

func generateSecret() string {
	cmd := exec.Command("openssl", "rand", "-hex", "32")
	output, err := cmd.Output()
	if err == nil && len(output) > 0 {
		return strings.TrimSpace(string(output))
	}

	// Fallback to less secure method
	return fmt.Sprintf("generated-%d", os.Getpid())
}
