version: "2"

linters:
  enable:
    - bodyclose
    - dogsled
    - errorlint
    - gocritic
    - gocyclo
    - godot
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - sqlclosecheck
    - staticcheck
    - wrapcheck
  disable:
    - errcheck
    - gosec
    - revive

run:
  tests: true
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0